[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.92.2"
  HUGO_ENABLEGITINFO = "true
  
[context.production.environment]
  HUGO_VERSION = "0.92.2"
  HUGO_ENABLEGITINFO = "true
  HUGO_ENV = "production"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.92.2"
  
[context.deploy-preview.environment]
  HUGO_VERSION = "0.92.2"

