[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.92.2"
  HUGO_ENABLEGITINFO = "true"
  
[context.production.environment]
  HUGO_VERSION = "0.92.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"