---
title: "Darkside"
author: "Fiona H Evans"
date: 2022-07-01T00:00:00Z
fontsize: 12pt
css: "styles.css"
categories: ["Short stories"]
tags: ["Short stories"]
share: false
---

I penned the first draft of 'Darkside' as part of my homework for a short story course presented by Maria Bonar from the [Society of Women's Writers Western Australia](https://www.swwofwa.com.au/whats-on.html).

The prompt was to write a story set in a mortuary. Normally more character-driven,  I enjoyed the focus on setting although my writing style jumps around a little as I move between setting description and character-driven action. Nevertheless, I love the story and think it has a certain charm to it. 

I was enormously pleased that it was accepted for publication in the very first edition of [Haunted Words Press](https://www.hauntedwordspress.com/home), a new digital literary zine focusing on tales of the gothic, the peculiar, and the downright spooky for middle grade and young adults. 

You can read it here: [Darkside](https://www.hauntedwordspress.com/issues).
