---
title: "A new day"
author: "Fiona H Evans"
date: 2022-04-06T00:00:00Z
fontsize: 12pt
css: "styles.css"
categories: ["Short stories", "Flash fiction"]
tags: ["Short stories", "Flash fiction"]
---



Marie takes a sip of her cocktail. She twirls the paper umbrella and glances across the table.

“Am I supposed to be scared now?”

“I’m not saying that.”

He reaches over and grasps her hand. 

“No, really,” he says. “There’s nothing to be scared of.”

He straightens up and looks back at the entrance to the restaurant. He seems to be looking for something or someone. His hand feels clammy in hers.

“I don’t know why I let you talk me into this,” she says. “I work in a morgue. I’ve seen more dead bodies than you can imagine. I’ve seen real monsters, Michael.”

She looks up with a mischievous smile.

“I’ve seen real monsters and they’re nothing like you.”

He leans over the table, his eyes searching hers.

“I’m not a monster, Marie. I’m just a man.” 

Marie tears her hand away and clasps it between her thighs. 

“Not a monster, just a man who wants to do monstrous things,” she says.

“You can’t pull out now, you took my deposit. Let’s go over the plan one more time.”

“Okay,” Marie pouts. “Next new moon, I lock up as usual, but I put the spare key under the rock.”

“The reddish-coloured rock, under the Mr Lincoln.”

“The what?”

“The rose bush, with the crimson flowers.”

“Yeah, right. I put the key under the reddish rock under the red roses.”

“You go home, but come back at midnight.”

“I don’t know why it has to be so late.”

“We have to wait until it is completely dark. No one can know, especially not her family. They must
think she’s cremated, and they can’t know about me.”

“Because they think you’re dead.”

“Everyone thinks I’m dead already.” He pauses. “What do you do next?”

Marie finishes her drink with a slurp, rubs her finger around the inside of the glass and sucks it dry.

“Then I help you get the body out of the freezer.”

“She has a name, Marie. It’s Ashley. We lift Ashley out of the freezer”

“Then what?”

“We dress her. I brought a dress. It was her favourite.”

Michael hands Marie a dress. The deep blue fabric is splashed with yellow flowers bright as the sunshine 
outside.

“Sunflowers?”

“She said they reminded her that every morning is the start of a new day.”

Marie is bored. She signals the waiter and orders another cocktail. 

“And then you’ll bury her.”

“It has to be in the right place. You know the place?”

“At the back of the cemetery, the empty part, under the ash tree.”

A man wearing a dark suit enters the restaurant. Michael beckons him, flashes a bank receipt and pockets 
the bundle the man passes over. It smells oily and rank, like day-old perfume on an unwashed body. Marie 
feels a sudden urge to leave.

Michael turns to her and asks one last time, “You understand, don’t you?”

“She’ll rise at dawn, but she’ll be hungry.”

“That’s why you can’t stay.”

“It will never work, you know.”

Michael rubs at the patch of rotting flesh just inside his collar. 

“Oh, I think it will. I just don’t know how long it will last.”

### Prompt

Write a story that is mainly dialogue.
