---
title: "Release"
author: "Fiona H Evans"
date: 2022-02-01T00:00:00Z
fontsize: 12pt
css: "styles.css"
categories: ["Short stories", "Flash fiction"]
tags: ["Short stories", "Flash fiction"]
---



The melody was familiar. How did the words go? Brown sugar. A good choice. I snatch up the phone.

“Do you have it?”

“Twice your usual. Like you wanted.”

I race downstairs and into the street. He slumps against the alley wall, away from the glare of streetlights. 

A flash of a smile as I hand him the cash.

“I’ll see you next week,” he says before striding into the darkness.
But he won’t.

Upstairs, I find a limpid vein purpled against greying flesh. 

Squeeze. Pat. Jab. Release.

I sigh. It’s done. Now I just have to wait.

It starts slowly.Tension eases and muscles relax. Her eyes open and she sits up, leans forward and wraps her arms around me.

“My good boy. My dear son.”

I smooth her hair and stroke her face. Avoid looking at the mass distending her night gown.

“How do you feel?” I ask.

“Better.”

“Don’t worry, Mum. It will be over soon.”

### Prompt

Write a story that begins with a song.

