---
title: "Survival"
author: "Fiona H Evans"
date: 2022-02-08T00:00:00Z
fontsize: 12pt
css: "styles.css"
categories: ["Short stories", "Flash fiction"]
tags: ["Short stories", "Flash fiction"]
share: false
---


What do you pack when you have eight minutes to leave? 

I can barely hear my thoughts above the clamour of the alarm. I glance at a photograph above my bed. Mark is grinning at the camera with his arms wrapped around me. Both of us new recruits in crisply laundered fatigues. Before the decay set in. I snatch it off the wall, stuff it in my duffle and bolt out the door. 

Outside is pandemonium. People run in all directions, legs spinning and stumbling in desperate haste to escape. I stop dead, confused. It’s an army base. Everyone knows the evacuation procedure. Why aren’t they in the emergency assembly area? 
Then I see the bodies. 

Sand sprays in the air as a bullet slams into the ground in front me. I immediately hunch into a crouch and sprint for cover. There isn’t much. I dash across the bitumen parking area and over an immaculate lawn bordered with white-painted rock. Beyond that there is only red dirt, grass and occasional slabs of stone jutting into the sky. I make for the nearest, zigzagging and twitching at every shot. I pause for only a moment until I see a cluster of boulders offering more substantial shelter.

As I move further away, the sound of screaming fades. I squeeze myself into a cleft between the rocks and huddle in the shade. Sweat soaks my shirt and runs down my back. I am rank with fear. My hands tremble and I steady them against warm stone. I breathe slowly to calm myself and peer out toward the base where it shimmers in the afternoon heat. I watch as the refectory bursts apart. Walls explode into chunks of concrete and shattered glass glitters in the sunlight. The noise of the blast sets my ears ringing. 
Dry heat sears my throat. I rummage through my bag, panicking until I find a water bottle. I could die without water. I use the back of my arm to wipe dust from my lips and take a few sips, saving the rest for later.

I need to make a plan. I can’t return to the remains of the base. The shooter could still be there. It’s twenty kilometres to the nearest town. I’ll wait until nightfall and hike there when the heat of the day fades. 

I stay in my hideout until the sky burns orange and red and then the lights go out completely. Shouldering my bag, I move out. I pause in the dark and listen to the howling of the wind. I look to the stars in the sky to set my direction. The air cools rapidly, but sweat still rolls down my temples. I’m trained, but I’ve never seen combat. 

I haven’t walked for more than ten minutes when a shot rings out. I instinctively dive for a shallow depression, scraping my hands and face raw on the rocky soil. I huddle panting in the darkness. I can’t stay here. He has night vision. I’m exposed. 

I take a deep breath, steel myself and scramble to the top of the ridge. A dark figure is silhouetted against the starry sky. He’s moving fast, tracking me. I run.

The next shot grazes my shoulder. Blood runs down my arm and soaks the torn fabric. I drop my bag to increase my pace. Bullets patter the ground at my heels as I duck behind a rocky outcrop. Gunshots pepper the granite but I’m covered, and they die away and quiet descends. I wonder who I’m up against, what he wants. My brain is scrambling, searching for a way out. 

Suddenly, sparks ricochet above my head. He’s circled around. 

There’s nothing I can do except try to lead him back. I scout the shadows for shelter. I take the long way around, darting from one rock to another. Deafening blasts of gunshot follow me. I hope he takes the bait.

A bullet tears through my calf. I scream and fall, lurch to my feet, and fall again. I’m crying with pain and terror, but I won’t give up. I’m so close. I drag myself along the ground using my arms and one good leg. I only stop when a boot strikes the side of my head, throwing me onto my back. 

He looms over me. The rifle never wavers as he removes his balaclava.

My eyes widen with recognition. 

“Mark!”

“You were the apple of my eye,” he says. 

I try to distract him.

“You planted the bomb.”

He stares unblinking at my face. 

“You betrayed me.” 

“You killed all those people.”

My fingers reach through the dust.

“You broke my heart.”

I grasp the strap. Slide down the zip. 

“We could have made it work,” I plead. “I’m sorry. I still love you.”

Mark lowers the gun to hang loosely at his side. He runs his hand over his buzzcut. 

“Jenny,” he groans. “You destroyed me.

I scramble through my pack but there’s nothing useful in there. Clothes. Phone. Hairbrush. Finally, my hand touches cold steel. 

I always pack my revolver.


### Prompt

Write a story that starts with the line "What do you pack when you have eight minutes to leave?"

