---
title: "This Writing Life"
author: "Fiona H Evans"
date: 2022-08-27T00:00:00Z
fontsize: 12pt
css: "styles.css"
categories: ["Blog"]
tags: ["Blog"]
share: false
---


I’m reading ‘This Writing Life’ by Annie Dillard.

She writes:

<blockquote>
Graham Greene noticed that since a novel “takes perhaps years to write, the author is not the same man at the end of the book as he was at the beginning...as though [the novel] were something he had begun in childhood and was finishing now in old age.”
</blockquote>

This is surely the case with “The Track” which I wrote 11 years ago when I was younger and less at ease with myself. The issues of fear and shame (which I only identified in revision as being the main theme and character arc) are closer to who I was then. I have changed and grown since, negotiating my own path to self-acceptance... mostly. My main fear now is that my writing is not good enough. I counsel myself that it is, that I can keep revising until I am happy, that it will be perfect. But, I still doubt.

Annie Dillard discusses how what we start writing, the early parts of the book, will inevitably be thrown away as we only truly know what the book is about when we have finished it. Sigh. I still have so much work to do.

But, now I will have some help!

I've signed up for the Australian Writers' Centre 
 [Write Your Novel](https://www.writerscentre.com.au/store/courses/write-your-novel/) six-month course, which starts Monday. During the course, I and each of the other 15 participants will submit our synopsis and three 5,000 word extracts. We will all read each others' work and provide feedback, as will our tutor. In January, we'll share our entire novel with three team members for structural edits. Then our tutor will provide feedback on our climaxes and resolutions. 
 
I'm excited to start. I’ve been working on this story for a while, and I want to know if it works. Does it engage the reader and make them want to read on? Does it capture the beauty of WA? Is my protagonist, Lee, likeable? Does the plot work to illuminate her character arc from shame to self-respect? With feedback from my classmates and tutor, I will revise  my story into a novel that captivates readers from the start and inspires them to make positive changes in their lives. 