---
title: "Portal"
author: "Fiona H Evans"
date: 2022-03-06T00:00:00Z
fontsize: 12pt
css: "styles.css"
categories: ["Furious fiction"]
tags: ["Furious fiction"]
share: false
---



You always hated Perth with its clean streets. There’s nowhere to hide from the wind or the heat. And the heat is on you now. 

You’re a scrawny kid, small for your age but a practiced pickpocket with fast fingers and feet. The problem is the city shuts down at the end of each day. Executives in shiny suits abandon the city by car and bus and electric scooter. There are no marks. You had to up your game. You took a risk. 

Footsteps thunder behind you. You look over your shoulder and glimpse two blue-clad policemen. 

One shouts, “We’ve got you now, Zach Zeus.”

You pick up the pace. You never mean to stay so long anyway. It’s time to move on.

You’re leaving them behind when you see something in the distance. Or rather, someone.
A dark figure silhouetted with a golden halo. It’s Marjory Parkes, a skinny street kid with a freckled face and ginger hair that shines in the sun.

You hadn’t planned on Marjory, but you can’t stop now. 

You dash toward her and grab her hand.

“Can’t talk. Follow me!”

You’re running together now. Hand in hand with Marjory Parkes. There was a time you’d have done anything to be holding her hand. 

Now your mind buzzes as you adapt your plan to fit her. You can’t leave her to be caught by the fuzz. 

The street forks and Marjory tugs you to the left.

“There’s an alley,” she says. 

You duck inside. The walls are grey concrete. Too clean but a perfect canvas. You reach into your pockets and find it. Unused since you came here. Since you met her. 

You reach as high as you can and draw a line down to the ground. A step to the right and you’re ready to draw another when a shadow falls. The cops are coming in. 
You drag the chalk down. Jump back up to complete the rectangle. 

“We’ve got you now. There’s no way out, Zach.” 

They’re getting closer. 

You sketch a handle and use it to open the door. The dank smell of rot and manure wafts out. Rats scatter and pigeons take to the wing. Clamouring voices fill the air. The muffled form of a vagrant huddles inside. He flops out his penis and pisses a river. This alley is more your style.  

You turn to Marjory. Your face is a question, your eyebrows so high they hurt.

You see the sunlight glint in her eye. 

She steps through the portal and you follow. 


### Furious Fiction March 2020

Include:

•	A character who commits a crime

•	Some kind of door being opened

•	The words: chalk, talk and fork


